### ISSUE TITLE
Open links from modal in new tab

### ISSUE THREAD

**Issue by aclist** [aclist/kbin-megamod#31]
Yea or nay?

**Comment by artillect** [comment]
Personally I prefer things not opening in new tabs by default so I can choose whether or not to do it, but I could be convinced otherwise

**Comment by aclist** [comment]
Right, I suppose you can middle click or whatever to open it. I just feel strangely about it because the expectation on normal links on a page is usually that they don't open in a new tab, but on a "menu," so to speak, you might want to open external links like the bug report page without having the whole page change on you.  Don't think it matters much one way or another.

**Comment by NamandeepNegi** [comment]
yea ,
